### ISSUE TITLE
Deliver jpa-api Specification Version update for Jakarta EE 9

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jpa-api#242]
**Is your feature request related to a problem? Please describe.**
Jakarta EE 9 is the next major release, with the main focus of moving from the ```javax``` namespace to the ```jakarta``` namespace.

**Describe the solution you'd like**
This issue will be used to track the progress of this work effort via the [Jakarta EE 9 Project board](https://github.com/orgs/eclipse-ee4j/projects/17).

**Additional context**
[Jakarta EE Specification Process](https://jakarta.ee/about/jesp/)
[Eclipse Project Handbook](https://www.eclipse.org/projects/handbook/#release)
[Eclipse Release Record for Jakarta EE 9](https://projects.eclipse.org/projects/ee4j.jakartaee-platform/releases/9)

**ToDo**
- [x] **[Create Eclipse Release Record](https://www.eclipse.org/projects/handbook/#pmi-commands-release) in your respective Jakarta Specification Project.**
 Most Component Release Records will just reference the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan).  But, if your Component deviates at all from the Platform Release Plan, then a description of the changes will be required in the Release Record.
- [x] ~~**Initiate a ballot for your Jakarta Release Record/Plan.**~~ - N/A
 Again, if your component is only doing the required minimum as defined by the [Jakarta EE 9 Platform Release Plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan), then no separate ballot is required.  You are already approved.  But, if your component deviates from the Platform Release Plan, then you will need to initiate your own ballot as defined by the [Jakarta EE Specification Process](https://jakarta.ee/about/jesp/).
- [x] **Jakarta-ize your Specification document (if applicable)**
 Many of the Jakarta EE components now have the source for their Specification documents.  It is strongly recommended that these Specification documents are properly updated to represent Jakarta EE instead of Java EE.  Some [helpful instructions are documented](https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc) here.
- [x] **javax -> jakarta Spec updates**
 If your component has Specification source, then all javax package references need to be updated to use jakarta package references.
- [x] **javax -> jakarta API updates**
 Your component APIs need to move from using the javax namespace to using the jakarta namespace.
- [x] **Release Candidate (RC) of Jakarta API in Maven Central**
 A Release Candidate of your component API should be pushed to Maven Central as soon as humanly possible.  This will allow other dependent components to utilize your APIs as they are updating their APIs.  Multiple revisions of these Release Candidate APIs are allowed (and probably expected) during the development cycle.
- [x] **javax -> jakarta TCK updates**
 Your component TCK needs to be updated to use the jakarta namespace.
- [x] **javax -> jakarta Compatible Implementation updates**
 Your compatible implementation that will be used to demonstrate completeness of the Specification needs to be updated to use the jakarta namespace.
- [x] **Final Jakarta API available in Staging Repo**
 When ready, your final version of the API needs to be staged to get ready for the PR review and approvals.
- [x] **Draft Specification and Apidoc PRs ready for review**
 Like we did for Jakarta EE 8, draft PRs need to be created and reviewed in preparation for the final ballots.
- [x] **Release Review Ballot started**
 Each Jakarta EE component will need to initiate a separate Release Review ballot after proper reviewing has completed.  To be clear, there will not be a blanket Release Review for all of Jakarta EE 9 like we did for the Plan Review.  Each component needs a separate Release Review.

**Comment by kwsutter** [comment]
Can I ask this team to please create and assign the following labels to this Issue?  Thank you!
[Epic]
[wave:0]

**Comment by jgrassel** [comment]
I'll look into "Create Eclipse Release Record in your respective Jakarta Specification Project." this afternoon

**Comment by jgrassel** [comment]
I've submitted the questionnaire as part of the create release record.  Some of the submissions may need to be updated to correct values.  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21532

**Comment by jgrassel** [comment]
@kwsutter FYI, Created the [release record for Jakarta EE 9](https://projects.eclipse.org/projects/ee4j.eclipselink/releases/3.0-jakarta-persistence-api)

**Comment by jgrassel** [comment]
Also created a release record for [Eclipselink 3.0](https://projects.eclipse.org/projects/ee4j.eclipselink/releases/3.0-jakarta-persistence-api)

**Comment by jgrassel** [comment]
I am going to check off javax -> jakarta API updates, as this was already accomplished by #231.
```
commit 30b92979321d42136f446033af4af93e00eb5ec4
Author: Scott Marlow <scott.marlow@gmail.com>
Date:   Mon Jan 13 07:00:14 2020 -0500

    change from javax.* to jakarta.* (#231)
    
    * change from javax.* to jakarta.*
    
    Signed-off-by: Scott Marlow <smarlow@redhat.com>
    
    * remove some of the TODOs for switch to jakarta property names and fix PeristenceProvider typo, more about TCK dependency, mention logger subsystem name
    
    Signed-off-by: Scott Marlow <smarlow@redhat.com>
```

**Comment by jgrassel** [comment]
Jakarta Persistence API 3.0 Spec Doc pull request - https://github.com/eclipse-ee4j/jpa-api/pull/255

**Comment by moghaddam** [comment]
I'm going to update the specification document (mentioned as **Jakarta-ize your Specification document** in the description) based on [Converting Java EE Specification Documents to Jakarta EE](https://github.com/jakartaee/specification-committee/blob/master/steps_javaee_to_jakartaee.adoc)

**Comment by jgrassel** [comment]
Are we finished with all of the updates to the Jakarta Persistence 3.0 spec doc?

**Comment by lukasj** [comment]
@jgrassel I'm going through the doc this week, for today, I have #289 Other than that, we may want to get rid of requirements related to persistence 1.0 at least, possibly also 2.0 (in short make everything <3.0 optional)

**Comment by arjantijms** [comment]
Ballot completed and approved: https://eclipse.org/lists/jakarta.ee-spec/msg01092.html

**Comment by lukasj** [comment]
done
